Us furkan
aldaitzwild/Pimp_Agency pull request #29
Opened 2021-04-23 08:48 UTC by furkanKrdmr

Made the title change function for previous and next !!!

2021-04-26 14:14 UTC, aldaitzwild requested changes

2021-04-26 14:14 UTC, aldaitzwild commented on public/assets/css/_Custom.css
> +>>>>>>> origin/dev
Unresolved conflict !

2021-04-28 08:41 UTC, aldaitzwild requested changes
You have a conflict with the dev branch : 

public/assets/script/script.js
src/View/Home/index.html.twig

2021-04-28 11:23 UTC, aldaitzwild requested changes
Your branch conflicts with dev

2021-04-28 15:27 UTC, aldaitzwild requested changes

2021-04-28 15:27 UTC, aldaitzwild commented on pimpbdd.sql
> +>>>>>>> origin/dev
Nice conflict ! Maybe you should fix that before I merge and the code for everyone

2021-04-28 15:27 UTC, aldaitzwild commented on pimpbdd.sql
> +>>>>>>> origin/dev
Another very good conflict

2021-04-28 15:27 UTC, aldaitzwild commented on src/View/Custom/custom.html.twig
> +        <input type="submit" value="Enregister">
Don't put default value in the input. It could cause some problems.

2021-04-28 15:27 UTC, aldaitzwild commented on src/View/Home/index.html.twig
> +	{% include "Home/vitrine.html.twig" %}
You include vitrine.html.twig twice ??

2021-04-28 15:40 UTC, furkanKrdmr commented on pimpbdd.sql
> +>>>>>>> origin/dev
this is not normal ...

2021-04-29 08:43 UTC, aldaitzwild requested changes
There are still changes to do

2021-04-29 09:07 UTC, closed without merging