Us01
aldaitzwild/Pimp_Agency pull request #9
Opened 2021-04-15 10:40 UTC by Jouannetaud

2021-04-15 15:35 UTC, aldaitzwild requested changes
Careful ! This PR is in conflict with the dev branch.
So you have merge the dev branch into yours and push it bask on github.

2021-04-15 18:36 UTC, Jouannetaud commented
conflit de la pull request corrigés

2021-04-16 06:58 UTC, aldaitzwild requested changes

2021-04-16 06:58 UTC, aldaitzwild commented on public/assets/script/script.js
> +>>>>>>> origin/dev
No ! This has still conflict in it !

2021-04-16 09:21 UTC, closed without merging